---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: unmount /tmp
      shell: "umount --lazy /tmp"
    - name: remove /tmp entry from /etc/fstab
      mount:
        path: /tmp
        state: absent
