---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: add /var entry to /etc/fstab
      mount:
        path: /tmp
        src: tmpfs
        fstype: tmpfs
        opts: defaults,noauto,noexec,nosuid
        dump: '1'
        state: mounted

